### ISSUE TITLE
How to extract field results from MilvusSearchResult?

### ISSUE THREAD

**Issue by mnns** [milvus-io/milvus-sdk-csharp#28]
var searchResults = await milvusClient.SearchAsync(
                MilvusSearchParameters.Create(collectionName, "text_vectors", search_output_fields)
                    .WithVectors(search_vectors)
                    .WithOutputFields(new List<string>() { "text" })
                    .WithConsistencyLevel(MilvusConsistencyLevel.Strong)
                    .WithMetricType(MilvusMetricType.L2)
                    .WithTopK(topK: (int)topResults)
                    .WithParameter("nprobe", "10")
                    .WithParameter("offset", "5"));

Trying to extract field "text". the only way I found is: searchResults.Results.FieldsData.Where(fd => fd.FieldName == "text").ToList().First().ToGrpcFieldData().Scalars.StringData.Data[0], which is extremely nasty.

The overall tabular encapsulation in this SDK (getting a flat table and not a simple enumrable object list) is really hard to work with.
Instead of getting a clear object that represents an object in the db, I need to iterate all results and build them myself, manually.

**Comment by weianweigan** [comment]
For store different type data, we use a abstract class(Field), You can try to cast it to match your field schema, such as 
```
var textField = searchResults.Results.FieldsData.Where(fd => fd.FieldName == "text").First() as Field<string>;
// Then access field by data properties.
textField.Data
```
---
We have used a new API in version 2.2.2, but the documentation is still for version 2.2.1.
Version 2.2.2 has updated a lot of content, including the removal of support for Restful APIs. We will update the documentation and NuGet packages in the next few days.
It is recommended that you use the latest 2.2.2 version because it has passed more tests and better api, but existing notebooks may not be useful as a reference anymore. You can refer to the [test cases](https://github.com/milvus-io/milvus-sdk-csharp/tree/main/Milvus.Client.Tests).

You can use it with **IO.Milvus, 2.2.2-preview.1**.

And simple doc (here)[https://github.com/milvus-io/milvus-sdk-csharp/tree/doc_for_newversion]
